// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class AdditionalInfo
{
    public int InfoId { get; set; }

    public string Position { get; set; }

    public string FullName { get; set; }

    public int? Code { get; set; }

    public int? Value { get; set; }

    public string Notes { get; set; }

    public DateOnly TransactionDate { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModifiedAt { get; set; }

    public int BranchId { get; set; }

    public virtual Branch Branch { get; set; }
}