// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class DailyBalance
{
    public int BalanceId { get; set; }

    public int? BranchId { get; set; }

    public DateTime? BalanceDate { get; set; }

    public decimal? OpeningBalance { get; set; }

    public decimal? ClosingBalance { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsReviewed { get; set; }

    public virtual Branch Branch { get; set; }
}