// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int? BranchId { get; set; }

    public int? UserId { get; set; }

    public DateTime TransactionDate { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string Type { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual User User { get; set; }
}