// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public int? BranchId { get; set; }

    public int? GroupId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual UserGroup Group { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}